<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MahApps.Metro" Version="3.0.0-rc0529" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkTogether.Data\WorkTogether.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="_core\List\AccountantList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\BayList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\BookingList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\CivilityList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\CompanyList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\IndividualList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\OfferList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\ServiceCallList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\ServiceCallTypeList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\TechnicianList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\UnitList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\UserList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\StaffList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\PriceList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="_core\List\ClientList.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="TechnicianView\ReallocationForm">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
